# .github/workflows/main.yml 내용 중 일부
      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crawler.py
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@github.com'
          git add last_posts.json
          git commit -m "Update last posts data" || exit 0
          git push
